WebProgramming/7. MODEL DOĞRULAMA (MODEL VALIDATION) - 1/ModelDogrulama_ModelValidation/ModelDogrulama_ModelValidation/Models/ErrorViewModel.cs
namespace ModelDogrulama_ModelValidation.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebProgramming/7. MODEL DOĞRULAMA (MODEL VALIDATION) - 1/ModelDogrulama_ModelValidation/ModelDogrulama_ModelValidation/Models/Ogrenci.cs
using System.ComponentModel.DataAnnotations;

namespace ModelDogrulama_ModelValidation.Models
{
    public class Ogrenci
    {
        [Required(ErrorMessage = "Isim Alani Zorunludur.")]
        [Display(Name = "Ad Soyad")]
        public string AdSoyad { get; set; }

        [Required(ErrorMessage = "Cinsiyet Secilmelidir.")]
        public string Cinsiyet { get; set; }

        [Range(1, 6, ErrorMessage = "Secilen Sinif 1-6 Arasinda Olmalidir.")]
        public int Sinif { get; set; }

        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Geçerli bir mail adresi giriniz")] 
        public string Email { get; set; }

    }
}

WebProgramming/7. MODEL DOĞRULAMA (MODEL VALIDATION) - 1/ModelDogrulama_ModelValidation/ModelDogrulama_ModelValidation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ModelDogrulama_ModelValidation.Models;
using System.Diagnostics;

namespace ModelDogrulama_ModelValidation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebProgramming/7. MODEL DOĞRULAMA (MODEL VALIDATION) - 1/ModelDogrulama_ModelValidation/ModelDogrulama_ModelValidation/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using ModelDogrulama_ModelValidation.Models;

namespace ModelDogrulama_ModelValidation.Controllers
{
    public class OgrenciController : Controller
    {
        static List<Ogrenci> ogrenciler=new List<Ogrenci>();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Ekle()
        {
            return View();
        }

        public IActionResult Liste()
        {
            return View(ogrenciler);
        }
        public IActionResult Kaydet( Ogrenci ogr)
        {
            if (ModelState.IsValid)
            {
                ogrenciler.Add(ogr); //Statice listeye ogrenci ekleniyor
                return View(ogr);
            }
            else
            {
                ViewBag.Hata = "Ogrenci Ekleme Basarisiz.";
                return View("Hata");
            }
            
        }
    }
}

WebProgramming/7. MODEL DOĞRULAMA (MODEL VALIDATION) - 1/ModelDogrulama_ModelValidation/ModelDogrulama_ModelValidation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModelDogrulama_ModelValidation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ModelDogrulama_ModelValidation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ModelDogrulama_ModelValidation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="Ekle">Ogrenci Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="Liste">Ogrenci Listele</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ModelDogrulama_ModelValidation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
@*     ASP.NET Core, istemci tarafı doğrulama kodu eklemeyi kolaylaştıran, doğrulama kütüphanesi içerir.Bunun için
    istemci tarafı doğrulama kütüphaneleri ( JQuery, jquery.validate & jquery.validate.unobtrusive) belirtilen sırada
    projeye dahil edilmelidir . Bu komut dosyalarının tüm viewler tarafından kullanılabilir olmaları için Layout
    dosyasında (_Layout.cshtml) ekli olmaları yeterlidir. *@

@*     Asp.net Core MVC projelerinde Jquery kütüphanesi shared klasörü altında yer alan “_Layout.cshtml”
    dosyasında aşağıdaki gibi eklidir. *@

@*     JQuery,jquery.validate & jquery.validate.unobtrusive yine shared klasörü altındaki
    _ValidationScriptsPartial.cshtml dosyası içinde aşağıdaki gibi eklenmiştir. Bu dosya da Layout.cshtml tarafından
    projeye eklenir. *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>